---
# Tasks file for installing deployment scripts

- name: Download deployment scripts
  block:
    - name: Clean artifact path
      file:
        state: absent
        path: "{{ deployment_scripts.destination }}"
      when: deployment_scripts.destination != ""

    - name: Get status of deployment destination directory
      stat: path="{{ deployment_scripts.destination }}"
      register: deployment_destination

    - name: Create deployment destination if not present
      file:
        path: "{{ deployment_scripts.destination }}"
        state: directory
      when: deployment_destination.stat.exists

    - name: Clone deployment repository path
      shell: "git clone {{ deployment_scripts.url }} {{ deployment_scripts.destination }}"

- name: Parse production destination paths
  block:
    - name: Build deployment production global config path
      file:
        path: "{{ deployment_scripts.destination }}/{{ deployment_scripts.prod_config }}"
      register: deployment_prod_config_file

    - name: Parse production global config YAML file
      set_fact:
        prod_config: "{{ lookup('file', deployment_prod_config_file.path) | from_yaml }}"

- include_tasks: create_destination_directory.yml
  with_items: "{{ lookup('dict', prod_config.directories) }}"
  loop_control:
    loop_var: dest_dir

- name: Parse test destination paths
  block:
    - name: Build deployment test global config path
      file:
        path: "{{ deployment_scripts.destination }}/{{ deployment_scripts.test_config }}"
      register: deployment_test_config_file

    - name: Parse test global config YAML file
      set_fact:
        test_config: "{{ lookup('file', deployment_test_config_file.path) | from_yaml }}"

- include_tasks: create_destination_directory.yml
  with_items: "{{ lookup('dict', test_config.directories) }}"
  loop_control:
    loop_var: dest_dir
