---
# Tasks file for installing deployment repository dependencies

- name: Install deployment dependencies with conda
  block:
    - name: Install App::cpanminus with conda
      shell: "conda install -c bioconda perl-app-cpanminus"

    - name: Install Getopt::Long with conda
      shell: "conda install -c bioconda perl-getopt-long"

    - name: Install Digest::MD5::File with conda
      shell: "conda install -c bioconda perl-digest-md5-file"

    - name: Install JSON with conda
      shell: "conda install -c bioconda perl-json"

    - name: Install File::Find::Rule with conda
      shell: "conda install -c bioconda perl-file-find-rule"

    - name: Install File::Slurp with conda
      shell: "conda install -c bioconda perl-file-slurp"

    - name: Install Test::Most with cpanm
      shell: "conda install -c bioconda perl-test-most"


- name: Install deployment dependencies with cpanm
  block:
    - name: Install Net::SCP with cpanm
      shell: "sudo cpanm Net::SCP"

    - name: Install Git::Repository with cpanm
      shell: "sudo cpanm Git::Repository"
      # Available via conda conda install -c dan_blanchard perl-git-repository 

    - name: Install YAML::XS with cpanm
      shell: "sudo cpanm YAML::XS"
    # Available via conda conda install -c eumetsat perl-yaml-xs