- name: Command to activate sanger-pathogens-deployment conda environment
  set_fact:    
    activate_deployment_env: "source {{apps.conda.base_dir}}/bin/activate sanger-pathogens-deployment"  

- name: Run production deployment
  shell: "{{activate_deployment_env}} && ./deploy.pl -e production"
  environment:
    CLASSPATH: "{{ env_vars.classpath }}"
  args:
    chdir: "{{ deployment_scripts.destination }}"
  when: not deployment_scripts.local

- name: Run local deployment
  shell: "{{activate_deployment_env}} && ./deploy.pl -e local"
  environment:
    CLASSPATH: "{{ env_vars.classpath }}"
  args:
    chdir: "{{ deployment_scripts.destination }}"
  when: deployment_scripts.local
