---

#####################################################################
#                                                                   #
#          CONFIGURING CONDA ON SANGER PATHOGEN MACHINES            #
#                                                                   #
#####################################################################

# Installs miniconda
# Sets conda channels
# Installs production conda environments
# Note: is set to fail if miniconda directories exist

- hosts: localhost

  roles:
    - {role: miniconda, tags: miniconda }
    - {role: sanger-pathogens-conda, tags: sanger-pathogens-conda }

