---

#####################################################################
#                                                                   #
#               CONFIGURING SANGER PATHOGEN MACHINES                #
#                                                                   #
#####################################################################

# Installs miniconda
# Installs default pathogen conda environment
# Sets up directories and installs deployment scripts
# Note: is set to fail if miniconda or deployment directories exist

- hosts: localhost

  roles:
    - {role: miniconda, tags: miniconda }
    - {role: pathogen-conda, tags: pathogen }
    - {role: deployment-scripts, tags: deployment }
