---
# Tasks file for configuring miniconda

- name: Add and check conda channels
  block:
    - name: Add conda channels
      shell: "{{ conda_exec }} config --add channels {{ item }}"
      loop: "{{ miniconda_channels }}"

    - name: Get conda channels
      shell: "{{ conda_exec}} config --get channels"
      register: returned_channels

    - name: Compare conda channels
      fail: msg="{{ item }} not found in channels"
      when: not returned_channels.stdout is search( item )
      loop: "{{ miniconda_channels }}"

