---
# Tasks file for miniconda

- name: Download miniconda installer
  register: miniconda_downloaded
  get_url:
    url={{ miniconda_installer.url }}/{{ miniconda_installer.file }}
    dest=/tmp/{{ miniconda_installer.file }}
    mode=0755

- name: Get miniconda version
  shell: "head /tmp/{{ miniconda_installer.file }} | grep VER: | awk '{print $3}'"
  register: grep_output

- debug: var=grep_output
