
---
# Sanger pathogen-specific variables
# The java classpath is for the deployment scripts and is set in the general repository
# https://gitlab.internal.sanger.ac.uk/sanger-pathogens/general/blob/master/java/sh/build.sh

install_prefix:
  miniconda: '/software/pathogen/external/apps'

apps:
  conda:
    base_dir: '/software/pathogen/external/apps/miniconda-4.5.12'

env_vars:
  classpath: '/software/pathogen/external/apps/usr/share/java' 