
---
# Sanger pathogen-specific variables
# The java classpath is for the deployment scripts and is set in the general repository
# https://gitlab.internal.sanger.ac.uk/sanger-pathogens/general/blob/master/java/sh/build.sh

install_prefix:
  miniconda: '/software/pathogen/external/apps'

apps:
  conda:
    base_dir: '/software/pathogen/external/apps/miniconda-4.5.12'

env_vars:
  classpath: '/software/pathogen/external/apps/usr/share/java' 

deployment_scripts: 
  # owner: pathdb
  # group: pathdev
  # mode: 0744
  # local: false
  local: true
  url: https://github.com/sanger-pathogens/deployment.git
  destination: /software/pathogen/projects/deployment
  branch: farm4-test
  checksum_log: '/software/pathogen/internal/prod/deployment_checksums.log'
  prod_config: "config/production/global.yml"
  test_config: "config/test/global.yml"
  local_config: "config/local/global.yml"

