---
# Tasks file for configuring miniconda

# This might be able to be removed, was required when testing with vagrant
# - name: Configure shell with conda init
#   shell: "{{ conda_exec }} init bash"

- name: Fail when no miniconda installation path is provided
  fail: msg="Failed as no miniconda installation path provided (apps.conda.base_dir)"
  when: apps.conda.base_dir is undefined

- name: Build conda bin directory path
  set_fact:
    conda_bin: "{{ apps.conda.base_dir  }}/bin"
  when: apps.conda.base_dir is defined

- name: Check whether conda bin directory exists
  include_role: 
    name: common
    tasks_from: validate_path
  vars:
    path_to_check: "{{ conda_bin }}"
    expect_directory: true
    fail_on_exist: false

- name: Set conda executable path
  set_fact:
    conda_exec: "{{ conda_bin  }}/conda"
  when: conda_bin is defined

- name: Add and validate conda channels
  block:
    - name: Add conda channels
      shell: "{{ conda_exec }} config --add channels {{ item }}"
      loop: "{{ miniconda_channels }}"

    - name: Get conda channels
      shell: "{{ conda_exec}} config --get channels"
      register: returned_channels

    - name: Compare conda channels
      fail: msg="{{ item }} not found in channels"
      when: not returned_channels.stdout is search( item )
      loop: "{{ miniconda_channels }}"

# This next step can take quite a while to run while conda solves the environment

- name: Import sanger-pathogens production conda environments
  block:
    - name: Clean artifact path
      file:
        state: absent
        path: "{{ sanger_pathogens.conda_repo_destination }}"
      when: sanger_pathogens.conda_repo_destination != ""

    - name: Clone sanger-pathogens repository
      shell: "git clone {{sanger_pathogens.conda_repo_url}} {{ sanger_pathogens.conda_repo_destination }}"
      
    - name: Import production conda environments
      shell: "{{ conda_exec }} env create -f {{ item }}"
      with_fileglob: "{{ sanger_pathogens.conda_repo_destination }}/environments/production/*.yml"

    - name: Clean artifact path
      file:
        state: absent
        path: "{{ sanger_pathogens.conda_repo_destination }}"


