---
# Tasks file for installing miniconda

- name: Build miniconda installer path
  set_fact: 
    miniconda_installer: "{{ installer.miniconda.destination_directory }}/{{ installer.miniconda.file }}"

- name: Download miniconda installer
  get_url:
    url={{ installer.miniconda.url }}/{{ installer.miniconda.file }}
    dest={{ miniconda_installer }}
    mode=0755

- name: Get miniconda version
  shell: "head {{ miniconda_installer }} | grep VER: | awk '{print $3}'"
  register: miniconda_version

- name: Set conda install directory path
  block:
    - name: Use install_prefix as defined
      set_fact:
        conda_base_directory: "{{ install_prefix.miniconda }}/miniconda-{{ miniconda_version.stdout }}"

- name: Check whether conda install directory exists
  include_role: 
    name: common
    tasks_from: check_path_status
  vars:
    path_to_check: "{{ conda_base_directory }}"
    fail_on_exists: true

- name: Install miniconda into conda dir
  command: "{{ miniconda_installer }} -b -p {{ conda_base_directory }}"
  args:
    creates: "{{ conda_base_directory }}"

- name: Delete miniconda installer
  file:
    path: "{{ miniconda_installer }}"
    state: absent

- name: Check whether conda bin directory exists
  include_role: 
    name: common
    tasks_from: check_path_status
  vars:
    path_to_check: "{{ conda_base_directory }}/bin"
    expect_directory: true
    fail_on_exist: false

- debug:
    msg: "Miniconda {{ miniconda_version.stdout }} installed in {{ conda_base_directory }}."