---
# Tasks file for installing miniconda

- name: Set miniconda installer path
  set_fact: 
    miniconda_installer_path: /tmp/{{ miniconda_installer.file }}

- name: Download miniconda installer
  register: miniconda_downloaded
  get_url:
    url={{ miniconda_installer.url }}/{{ miniconda_installer.file }}
    dest={{ miniconda_installer_path }}
    mode=0755

- name: Get miniconda version
  shell: "head {{ miniconda_installer_path }} | grep VER: | awk '{print $3}'"
  register: miniconda_version

- name: Set conda related variables
  block:
    - name: Set conda install directory path
      set_fact:
        conda_dir: "{{ install_prefix.dir }}/miniconda-{{ miniconda_version.stdout }}"
      when: conda_dir is undefined

- name: Fail if conda install directory exists
  block: 
    - name: Get status of conda install directory  
      stat: path="{{ conda_dir }}"
      register: conda_dir_status

    - name: Fail if directory exists
      fail: msg="The conda install directory already exists"
      when: conda_dir_status.stat.exists

- name: Install miniconda into conda dir
  command: "{{ miniconda_installer_path }} -b -p {{ conda_dir }}"
  args:
    creates: "{{ conda_dir }}"
  when: not conda_dir_status.stat.exists

- name: Delete miniconda installer
  file:
    path: "{{ miniconda_installer_path }}"
    state: absent

- name: set conda executable paths 
  block:
    - name: set conda exec path
      set_fact:
        conda_exec: "{{ conda_dir }}/bin/conda"

    - name: set conda activate exec path
      set_fact:
        conda_activate: "{{ conda_dir }}/bin/activate"    

    - name: set conda deactivate exec path
      set_fact:
        conda_deactivate: "{{ conda_dir }}/bin/deactivate"     

- name: Fail if conda executable path doesn't exist
  block: 
    - name: Get status of conda executable
      stat: path="{{ conda_exec }}"
      register: conda_exec_status

    - name: Fail if conda exec doesn't exist
      fail: msg="The conda executable doesn't exist"
      when: not conda_exec_status.stat.exists
