---
# Tasks file for installing miniconda

- name: Build destination for miniconda installer script
  set_fact: 
    miniconda_installer: "{{ installer.miniconda.destination_directory }}/{{ installer.miniconda.file }}"

- name: Download miniconda installer script
  get_url:
    url={{ installer.miniconda.url }}/{{ installer.miniconda.file }}
    dest={{ miniconda_installer }}
    mode=0755

- name: Get miniconda version from miniconda installer script
  shell: "head {{ miniconda_installer }} | grep VER: | awk '{print $3}'"
  register: miniconda_version

- name: Build miniconda installation path
  block:
    - name: Use install_prefix to build conda install path (conda_base_directory)
      set_fact:
        miniconda_install_path: "{{ install_prefix.miniconda }}/miniconda-{{ miniconda_version.stdout }}"

- name: Check whether miniconda installation path exists
  include_role: 
    name: common
    tasks_from: check_path_status
  vars:
    path_to_check: "{{ miniconda_install_path }}"
    fail_on_exists: true

- name: Install miniconda into miniconda installation path
  command: "{{ miniconda_installer }} -b -p {{ miniconda_install_path }}"
  args:
    creates: "{{ miniconda_install_path }}"

- name: Delete miniconda installer script
  file:
    path: "{{ miniconda_installer }}"
    state: absent

- name: Check whether miniconda bin directory exists
  include_role: 
    name: common
    tasks_from: check_path_status
  vars:
    path_to_check: "{{ miniconda_install_path }}/bin"
    expect_directory: true
    fail_on_exist: false

- debug:
    msg: "Miniconda {{ miniconda_version.stdout }} installed in {{ miniconda_install_path}}."